name: Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  CT_VERSION: "3.2.0"
  KUBEVAL_VERSION: "0.15.0"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: lint
          config: .github/ct.yaml
  
  kubeval:
    runs-on: ubuntu-latest
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        k8s:
          - 1.16.4
          - 1.17.4
          - 1.18.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: script/kubeval.sh

  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - lint
      - kubeval
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
